/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario */
        get: operations["get_scenario_api_scenario_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run */
        get: operations["stream_run_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/dispute-resolution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Dispute */
        post: operations["resolve_dispute_api_runs__run_id__dispute_resolution_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Approval */
        post: operations["decide_approval_api_runs__run_id__approval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Demo */
        post: operations["reset_demo_api_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionReceipt */
        ActionReceipt: {
            /** Action Id */
            action_id: string;
            status: components["schemas"]["ActionReceiptStatus"];
            /** Receipt Ref */
            receipt_ref?: string | null;
            /** Detail */
            detail: string;
        };
        /**
         * ActionReceiptStatus
         * @enum {string}
         */
        ActionReceiptStatus: "ACCEPTED" | "REJECTED";
        /** AgentActivity */
        AgentActivity: {
            agent: components["schemas"]["AgentName"];
            /** Objective */
            objective: string;
            /** @default WAITING */
            status: components["schemas"]["AgentStatus"];
            confidence?: components["schemas"]["Confidence"] | null;
            /** Last Summary */
            last_summary?: string | null;
        };
        /**
         * AgentName
         * @enum {string}
         */
        AgentName: "Coordinator Agent" | "Impact Agent" | "Yard Agent" | "Recovery Agent" | "Execution Agent";
        /**
         * AgentStatus
         * @enum {string}
         */
        AgentStatus: "WAITING" | "RUNNING" | "COMPLETED" | "BLOCKED" | "FAILED";
        /** AlternativeSailing */
        AlternativeSailing: {
            /** Vessel Name */
            vessel_name: string;
            /** Replaces Onward Vessel */
            replaces_onward_vessel: string;
            /**
             * Departs
             * Format: date-time
             */
            departs: string;
            /**
             * Connection Cutoff
             * Format: date-time
             */
            connection_cutoff: string;
            /** Available Capacity */
            available_capacity: number;
        };
        /** AlternativeSailingResult */
        AlternativeSailingResult: {
            status: components["schemas"]["SailingLookupStatus"];
            /** Sailings */
            sailings: components["schemas"]["AlternativeSailing"][];
            /** Stale Notice */
            stale_notice?: string | null;
        };
        /**
         * ApprovalDecision
         * @enum {string}
         */
        ApprovalDecision: "APPROVED" | "REJECTED";
        /** ApprovalRequest */
        ApprovalRequest: {
            plan_archetype: components["schemas"]["PlanArchetype"];
            decision: components["schemas"]["ApprovalDecision"];
            /** Note */
            note?: string | null;
        };
        /** BlockForecast */
        BlockForecast: {
            /** Block Id */
            block_id: string;
            /** Container Capacity */
            container_capacity: number;
            /** Series */
            series: components["schemas"]["YardOccupancyPoint"][];
            /** Peak Occupancy */
            peak_occupancy: number;
            /**
             * Peak Time
             * Format: date-time
             */
            peak_time: string;
        };
        /**
         * CargoType
         * @enum {string}
         */
        CargoType: "PHARMA_REEFER" | "TIME_CRITICAL_MANUFACTURING" | "GENERAL_DRY";
        /**
         * Confidence
         * @enum {string}
         */
        Confidence: "HIGH" | "MEDIUM" | "LOW";
        /** ConnectionAnalysis */
        ConnectionAnalysis: {
            /** Delay Hours */
            delay_hours: number;
            /** Safe Count */
            safe_count: number;
            /** At Risk Count */
            at_risk_count: number;
            /** Missed Count */
            missed_count: number;
            /** Groups */
            groups: components["schemas"]["ConnectionGroupSummary"][];
            /** Connections */
            connections: components["schemas"]["ContainerConnection"][];
        };
        /** ConnectionGroupSummary */
        ConnectionGroupSummary: {
            /** Onward Vessel */
            onward_vessel: string;
            cargo_type: components["schemas"]["CargoType"];
            status: components["schemas"]["ConnectionStatus"];
            /** Container Count */
            container_count: number;
        };
        /**
         * ConnectionStatus
         * @enum {string}
         */
        ConnectionStatus: "SAFE" | "AT_RISK" | "MISSED" | "RESOLVED";
        /** ContainerConnection */
        ContainerConnection: {
            /** Container Id */
            container_id: string;
            cargo_type: components["schemas"]["CargoType"];
            /** Onward Vessel */
            onward_vessel: string;
            /**
             * Ready Time
             * Format: date-time
             */
            ready_time: string;
            /**
             * Connection Cutoff
             * Format: date-time
             */
            connection_cutoff: string;
            /** Margin Hours */
            margin_hours: number;
            status: components["schemas"]["ConnectionStatus"];
            /** Priority Rank */
            priority_rank: number;
            /** Priority Reason */
            priority_reason: string;
        };
        /** CostComponent */
        CostComponent: {
            /** Name */
            name: string;
            /** Amount */
            amount: number;
            /** Basis */
            basis: string;
        };
        /** CostEstimate */
        CostEstimate: {
            /** Components */
            components: components["schemas"]["CostComponent"][];
            /** Total */
            total: number;
            /**
             * Illustrative
             * @default true
             */
            illustrative: boolean;
        };
        /**
         * CreateRunRequest
         * @description Scenario controls plus explicit run-mode selection.
         */
        CreateRunRequest: {
            /**
             * Delay Hours
             * @default 18
             */
            delay_hours: number;
            /** @default BALANCED */
            priority_emphasis: components["schemas"]["PriorityEmphasis"];
            /**
             * Alternative Sailing Failure
             * @default true
             */
            alternative_sailing_failure: boolean;
            /** @default LIVE_STUB */
            mode: components["schemas"]["RunMode"];
        };
        /** Dispute */
        Dispute: {
            /** Dispute Id */
            dispute_id: string;
            /** Question */
            question: string;
            /** Positions */
            positions: components["schemas"]["DisputePosition"][];
            /** Confirmed Constraint */
            confirmed_constraint?: string | null;
            /**
             * Resolved By Human
             * @default false
             */
            resolved_by_human: boolean;
        };
        /** DisputePosition */
        DisputePosition: {
            agent: components["schemas"]["AgentName"];
            /** Position */
            position: string;
            /** Evidence */
            evidence: string[];
        };
        /** DisputeResolutionRequest */
        DisputeResolutionRequest: {
            /** Dispute Id */
            dispute_id: string;
            /** Confirmed Constraint */
            confirmed_constraint: string;
        };
        /** DisruptionAlert */
        DisruptionAlert: {
            /** Vessel Name */
            vessel_name: string;
            /** Port Call */
            port_call: string;
            /**
             * Original Eta
             * Format: date-time
             */
            original_eta: string;
            /**
             * Revised Eta
             * Format: date-time
             */
            revised_eta: string;
            /**
             * Event Time
             * Format: date-time
             */
            event_time: string;
            /**
             * Synthetic
             * @default true
             */
            synthetic: boolean;
            /** Delay Hours */
            readonly delay_hours: number;
        };
        /**
         * EventKind
         * @enum {string}
         */
        EventKind: "RUN_STARTED" | "AGENT_STARTED" | "TOOL_CALLED" | "AGENT_COMPLETED" | "HANDOFF" | "DISPUTE_OPENED" | "HUMAN_DECISION" | "APPROVAL_REQUIRED" | "ACTION_DISPATCHED" | "ERROR" | "RUN_COMPLETED";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** MockedAction */
        MockedAction: {
            /** Action Id */
            action_id: string;
            action_type: components["schemas"]["MockedActionType"];
            plan_archetype: components["schemas"]["PlanArchetype"];
            /** Description */
            description: string;
            /** Payload Summary */
            payload_summary: string;
        };
        /**
         * MockedActionType
         * @enum {string}
         */
        MockedActionType: "TERMINAL_WORK_ORDER" | "REEFER_CHECK" | "CARRIER_NOTICE";
        /** PlanAction */
        PlanAction: {
            action: components["schemas"]["RecoveryActionType"];
            /** Onward Vessel */
            onward_vessel: string;
            cargo_type: components["schemas"]["CargoType"];
            /** Container Count */
            container_count: number;
            /** Target Sailing */
            target_sailing?: string | null;
            /** Rationale */
            rationale: string;
        };
        /**
         * PlanArchetype
         * @enum {string}
         */
        PlanArchetype: "AGGRESSIVE_RUSH" | "STANDARD_REBOOK" | "OPTIMIZED_HYBRID";
        /** PlanComparison */
        PlanComparison: {
            /** Evaluations */
            evaluations: components["schemas"]["PlanEvaluation"][];
            recommended?: components["schemas"]["PlanArchetype"] | null;
            /** Rationale */
            rationale: string;
            confidence: components["schemas"]["Confidence"];
        };
        /** PlanEvaluation */
        PlanEvaluation: {
            plan: components["schemas"]["RecoveryPlan"];
            metrics: components["schemas"]["PlanMetrics"];
            /** Feasible */
            feasible: boolean;
            /** Rejection Reasons */
            rejection_reasons?: string[];
        };
        /** PlanMetrics */
        PlanMetrics: {
            cost: components["schemas"]["CostEstimate"];
            /** Missed Connections */
            missed_connections: number;
            /** Critical Cargo Protected Pct */
            critical_cargo_protected_pct: number;
            /** Yard Peak Occupancy Pct */
            yard_peak_occupancy_pct: number;
            /** Max Additional Delay Hours */
            max_additional_delay_hours: number;
        };
        /**
         * PriorityEmphasis
         * @enum {string}
         */
        PriorityEmphasis: "CARGO_PROTECTION" | "CONGESTION_REDUCTION" | "BALANCED";
        /**
         * RecoveryActionType
         * @enum {string}
         */
        RecoveryActionType: "RUSH" | "REBOOK" | "HOLD";
        /** RecoveryPlan */
        RecoveryPlan: {
            archetype: components["schemas"]["PlanArchetype"];
            /** Title */
            title: string;
            /** Actions */
            actions: components["schemas"]["PlanAction"][];
            /** Assumptions */
            assumptions?: string[];
        };
        /** ReeferShortage */
        ReeferShortage: {
            /** Block Id */
            block_id: string;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /** Required Plugs */
            required_plugs: number;
            /** Available Plugs */
            available_plugs: number;
        };
        /** RunCreated */
        RunCreated: {
            /** Run Id */
            run_id: string;
            mode: components["schemas"]["RunMode"];
            stage: components["schemas"]["WorkflowStage"];
            /** Events Url */
            events_url: string;
        };
        /**
         * RunMode
         * @enum {string}
         */
        RunMode: "LIVE_STUB" | "LIVE_GEMINI" | "DEMO_REPLAY";
        /** RunResults */
        RunResults: {
            connection_analysis?: components["schemas"]["ConnectionAnalysis"] | null;
            baseline_yard?: components["schemas"]["YardForecast"] | null;
            planned_yard?: components["schemas"]["YardForecast"] | null;
            alternative_sailings?: components["schemas"]["AlternativeSailingResult"] | null;
            plan_comparison?: components["schemas"]["PlanComparison"] | null;
            /** Dispatched Actions */
            dispatched_actions?: components["schemas"]["MockedAction"][];
            /** Receipts */
            receipts?: components["schemas"]["ActionReceipt"][];
        };
        /**
         * SailingLookupStatus
         * @enum {string}
         */
        SailingLookupStatus: "MOCK_SUCCESS" | "TIMEOUT_CACHED_FALLBACK";
        /** ScenarioControls */
        ScenarioControls: {
            /**
             * Delay Hours
             * @default 18
             */
            delay_hours: number;
            /** @default BALANCED */
            priority_emphasis: components["schemas"]["PriorityEmphasis"];
            /**
             * Alternative Sailing Failure
             * @default true
             */
            alternative_sailing_failure: boolean;
        };
        /** ScenarioState */
        ScenarioState: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            alert: components["schemas"]["DisruptionAlert"];
            /** Objective */
            objective: string;
            /** Planning Horizon Hours */
            planning_horizon_hours: number;
            controls: components["schemas"]["ScenarioControls"];
            /** Synthetic Notice */
            synthetic_notice: string;
        };
        /** TraceEvent */
        TraceEvent: {
            /** Event Id */
            event_id: string;
            /** Sequence */
            sequence: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            kind: components["schemas"]["EventKind"];
            stage: components["schemas"]["WorkflowStage"];
            agent?: components["schemas"]["AgentName"] | null;
            /** Objective */
            objective?: string | null;
            /** Input Summary */
            input_summary?: string | null;
            /** Tool */
            tool?: string | null;
            /** Decision Summary */
            decision_summary?: string | null;
            confidence?: components["schemas"]["Confidence"] | null;
            /** Assumptions */
            assumptions?: string[];
            /** Result */
            result?: string | null;
            /** Error */
            error?: string | null;
            /** Elapsed Ms */
            elapsed_ms?: number | null;
            next_handoff?: components["schemas"]["AgentName"] | null;
            /** Parallel Group */
            parallel_group?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkflowStage
         * @enum {string}
         */
        WorkflowStage: "READY" | "ASSESSING" | "DISPUTE" | "PLANNING" | "AWAITING_APPROVAL" | "EXECUTING" | "COMPLETE" | "FAILED";
        /** WorkflowState */
        WorkflowState: {
            /** Run Id */
            run_id: string;
            mode: components["schemas"]["RunMode"];
            stage: components["schemas"]["WorkflowStage"];
            scenario: components["schemas"]["ScenarioState"];
            /** Activities */
            activities: components["schemas"]["AgentActivity"][];
            /** Trace */
            trace?: components["schemas"]["TraceEvent"][];
            active_dispute?: components["schemas"]["Dispute"] | null;
            results?: components["schemas"]["RunResults"] | null;
        };
        /** YardForecast */
        YardForecast: {
            /** Horizon Hours */
            horizon_hours: number;
            /** Blocks */
            blocks: components["schemas"]["BlockForecast"][];
            /** Reefer Shortages */
            reefer_shortages: components["schemas"]["ReeferShortage"][];
        };
        /** YardOccupancyPoint */
        YardOccupancyPoint: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Occupancy */
            occupancy: number;
            /** Congested */
            congested: boolean;
            /** Full */
            full: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_scenario_api_scenario_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioState"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: {
                /** @description Overrides the body mode field. */
                mode?: components["schemas"]["RunMode"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_dispute_api_runs__run_id__dispute_resolution_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisputeResolutionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_approval_api_runs__run_id__approval_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_demo_api_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioState"];
                };
            };
        };
    };
}
