/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario */
        get: operations["get_scenario_api_scenario_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run */
        get: operations["stream_run_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Demo */
        post: operations["reset_demo_api_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentActivity */
        AgentActivity: {
            agent: components["schemas"]["AgentName"];
            /** Objective */
            objective: string;
            /** @default WAITING */
            status: components["schemas"]["AgentStatus"];
            confidence?: components["schemas"]["Confidence"] | null;
            /** Last Summary */
            last_summary?: string | null;
        };
        /**
         * AgentName
         * @enum {string}
         */
        AgentName: "Coordinator Agent" | "Impact Agent" | "Yard Agent" | "Recovery Agent" | "Execution Agent";
        /**
         * AgentStatus
         * @enum {string}
         */
        AgentStatus: "WAITING" | "RUNNING" | "COMPLETED" | "BLOCKED" | "FAILED";
        /**
         * Confidence
         * @enum {string}
         */
        Confidence: "HIGH" | "MEDIUM" | "LOW";
        /** Dispute */
        Dispute: {
            /** Dispute Id */
            dispute_id: string;
            /** Question */
            question: string;
            /** Positions */
            positions: components["schemas"]["DisputePosition"][];
            /** Confirmed Constraint */
            confirmed_constraint?: string | null;
            /**
             * Resolved By Human
             * @default false
             */
            resolved_by_human: boolean;
        };
        /** DisputePosition */
        DisputePosition: {
            agent: components["schemas"]["AgentName"];
            /** Position */
            position: string;
            /** Evidence */
            evidence: string[];
        };
        /** DisruptionAlert */
        DisruptionAlert: {
            /** Vessel Name */
            vessel_name: string;
            /** Port Call */
            port_call: string;
            /**
             * Original Eta
             * Format: date-time
             */
            original_eta: string;
            /**
             * Revised Eta
             * Format: date-time
             */
            revised_eta: string;
            /**
             * Event Time
             * Format: date-time
             */
            event_time: string;
            /**
             * Synthetic
             * @default true
             */
            synthetic: boolean;
            /** Delay Hours */
            readonly delay_hours: number;
        };
        /**
         * EventKind
         * @enum {string}
         */
        EventKind: "RUN_STARTED" | "AGENT_STARTED" | "TOOL_CALLED" | "AGENT_COMPLETED" | "HANDOFF" | "DISPUTE_OPENED" | "HUMAN_DECISION" | "APPROVAL_REQUIRED" | "ACTION_DISPATCHED" | "ERROR" | "RUN_COMPLETED";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * PriorityEmphasis
         * @enum {string}
         */
        PriorityEmphasis: "CARGO_PROTECTION" | "CONGESTION_REDUCTION" | "BALANCED";
        /** RunCreated */
        RunCreated: {
            /** Run Id */
            run_id: string;
            mode: components["schemas"]["RunMode"];
            stage: components["schemas"]["WorkflowStage"];
            /** Events Url */
            events_url: string;
        };
        /**
         * RunMode
         * @enum {string}
         */
        RunMode: "LIVE_STUB" | "LIVE_GEMINI" | "DEMO_REPLAY";
        /** ScenarioControls */
        ScenarioControls: {
            /**
             * Delay Hours
             * @default 18
             */
            delay_hours: number;
            /** @default BALANCED */
            priority_emphasis: components["schemas"]["PriorityEmphasis"];
            /**
             * Alternative Sailing Failure
             * @default true
             */
            alternative_sailing_failure: boolean;
        };
        /** ScenarioState */
        ScenarioState: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            alert: components["schemas"]["DisruptionAlert"];
            /** Objective */
            objective: string;
            /** Planning Horizon Hours */
            planning_horizon_hours: number;
            controls: components["schemas"]["ScenarioControls"];
            /** Synthetic Notice */
            synthetic_notice: string;
        };
        /** TraceEvent */
        TraceEvent: {
            /** Event Id */
            event_id: string;
            /** Sequence */
            sequence: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            kind: components["schemas"]["EventKind"];
            stage: components["schemas"]["WorkflowStage"];
            agent?: components["schemas"]["AgentName"] | null;
            /** Objective */
            objective?: string | null;
            /** Input Summary */
            input_summary?: string | null;
            /** Tool */
            tool?: string | null;
            /** Decision Summary */
            decision_summary?: string | null;
            confidence?: components["schemas"]["Confidence"] | null;
            /** Assumptions */
            assumptions?: string[];
            /** Result */
            result?: string | null;
            /** Error */
            error?: string | null;
            /** Elapsed Ms */
            elapsed_ms?: number | null;
            next_handoff?: components["schemas"]["AgentName"] | null;
            /** Parallel Group */
            parallel_group?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkflowStage
         * @enum {string}
         */
        WorkflowStage: "READY" | "ASSESSING" | "DISPUTE" | "PLANNING" | "AWAITING_APPROVAL" | "EXECUTING" | "COMPLETE" | "FAILED";
        /** WorkflowState */
        WorkflowState: {
            /** Run Id */
            run_id: string;
            mode: components["schemas"]["RunMode"];
            stage: components["schemas"]["WorkflowStage"];
            scenario: components["schemas"]["ScenarioState"];
            /** Activities */
            activities: components["schemas"]["AgentActivity"][];
            /** Trace */
            trace?: components["schemas"]["TraceEvent"][];
            active_dispute?: components["schemas"]["Dispute"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_scenario_api_scenario_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioState"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioControls"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_demo_api_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioState"];
                };
            };
        };
    };
}
