/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario */
        get: operations["get_scenario_api_scenario_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run */
        get: operations["stream_run_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/dispute-resolution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Dispute */
        post: operations["resolve_dispute_api_runs__run_id__dispute_resolution_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Approval */
        post: operations["decide_approval_api_runs__run_id__approval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/benchmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Benchmark */
        post: operations["create_benchmark_api_benchmarks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/benchmarks/{benchmark_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Benchmark */
        get: operations["stream_benchmark_api_benchmarks__benchmark_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/benchmarks/{benchmark_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Benchmark */
        get: operations["get_benchmark_api_benchmarks__benchmark_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Demo */
        post: operations["reset_demo_api_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionReceipt */
        ActionReceipt: {
            /** Action Id */
            action_id: string;
            status: components["schemas"]["ActionReceiptStatus"];
            /** Receipt Ref */
            receipt_ref?: string | null;
            /** Detail */
            detail: string;
        };
        /**
         * ActionReceiptStatus
         * @enum {string}
         */
        ActionReceiptStatus: "ACCEPTED" | "REJECTED";
        /** AgentActivity */
        AgentActivity: {
            agent: components["schemas"]["AgentName"];
            /** Objective */
            objective: string;
            /** @default WAITING */
            status: components["schemas"]["AgentStatus"];
            confidence?: components["schemas"]["Confidence"] | null;
            /** Last Summary */
            last_summary?: string | null;
        };
        /**
         * AgentName
         * @enum {string}
         */
        AgentName: "Coordinator Agent" | "Impact Agent" | "Yard Agent" | "Recovery Agent" | "Execution Agent";
        /**
         * AgentStatus
         * @enum {string}
         */
        AgentStatus: "WAITING" | "RUNNING" | "COMPLETED" | "BLOCKED" | "FAILED";
        /** AlternativeSailing */
        AlternativeSailing: {
            /** Vessel Name */
            vessel_name: string;
            /** Replaces Onward Vessel */
            replaces_onward_vessel: string;
            /**
             * Departs
             * Format: date-time
             */
            departs: string;
            /**
             * Connection Cutoff
             * Format: date-time
             */
            connection_cutoff: string;
            /** Available Capacity */
            available_capacity: number;
        };
        /** AlternativeSailingResult */
        AlternativeSailingResult: {
            status: components["schemas"]["SailingLookupStatus"];
            /** Sailings */
            sailings: components["schemas"]["AlternativeSailing"][];
            /** Stale Notice */
            stale_notice?: string | null;
        };
        /** AnchorComparison */
        AnchorComparison: {
            /** Anchor Key */
            anchor_key: string;
            /** Label */
            label: string;
            /** Recorded Value */
            recorded_value: number;
            recorded_provenance: components["schemas"]["SeriesProvenance"];
            /** Simulated Value */
            simulated_value: number;
            /** Unit */
            unit: string;
            /** Tolerance */
            tolerance: number;
            /** Within Tolerance */
            within_tolerance: boolean;
        };
        /**
         * ApprovalDecision
         * @enum {string}
         */
        ApprovalDecision: "APPROVED" | "REJECTED";
        /** ApprovalRequest */
        ApprovalRequest: {
            plan_archetype: components["schemas"]["PlanArchetype"];
            decision: components["schemas"]["ApprovalDecision"];
            /** Note */
            note?: string | null;
        };
        /** ArmComparison */
        ArmComparison: {
            arm: components["schemas"]["FleetArm"];
            versus: components["schemas"]["FleetArm"];
            /** Peak Wait Delta Days */
            peak_wait_delta_days: number;
            /** Peak Wait Reduction Pct */
            peak_wait_reduction_pct: number;
            /** Recovery Days Saved */
            recovery_days_saved?: number | null;
            /** Mean Wait Delta Days */
            mean_wait_delta_days: number;
            /** Wait Cost Delta Usd */
            wait_cost_delta_usd: number;
            /** Wins On Peak */
            wins_on_peak: boolean;
            /** Wins On Recovery */
            wins_on_recovery: boolean;
        };
        /** ArmResult */
        ArmResult: {
            arm: components["schemas"]["FleetArm"];
            /** Label */
            label: string;
            provenance: components["schemas"]["SeriesProvenance"];
            /** Is Simulation */
            is_simulation: boolean;
            /** Daily */
            daily: components["schemas"]["DailyKpi"][];
            metrics: components["schemas"]["FleetMetrics"];
            /** Decisions */
            decisions?: components["schemas"]["RecordedDecision"][];
            blind_audit?: components["schemas"]["BlindAuditSummary"] | null;
            calibration?: components["schemas"]["CalibrationReport"] | null;
            /** Caveat */
            caveat?: string | null;
        };
        /**
         * AuditVerdict
         * @enum {string}
         */
        AuditVerdict: "PASS" | "FAIL";
        /** BenchmarkConfig */
        BenchmarkConfig: {
            /** Seed */
            seed: number;
            /** Arms */
            arms: components["schemas"]["FleetArm"][];
            world: components["schemas"]["FleetWorldConfig"];
            /** @default SCRIPTED */
            brain: components["schemas"]["FleetBrainMode"];
            /**
             * Rolling Window Days
             * @default 3
             */
            rolling_window_days: number;
            /**
             * Recovery Threshold Days
             * @default 2
             */
            recovery_threshold_days: number;
            /**
             * Recovery Sustain Days
             * @default 5
             */
            recovery_sustain_days: number;
        };
        /** BenchmarkCreated */
        BenchmarkCreated: {
            /** Benchmark Id */
            benchmark_id: string;
            stage: components["schemas"]["BenchmarkStage"];
            /** Events Url */
            events_url: string;
            /** Playback Notice */
            playback_notice: string;
        };
        /** BenchmarkEvent */
        BenchmarkEvent: {
            /** Event Id */
            event_id: string;
            /** Sequence */
            sequence: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            kind: components["schemas"]["BenchmarkEventKind"];
            arm?: components["schemas"]["FleetArm"] | null;
            day?: components["schemas"]["DailyKpi"] | null;
            decision?: components["schemas"]["RecordedDecision"] | null;
            /** Message */
            message: string;
            /** Error */
            error?: string | null;
        };
        /**
         * BenchmarkEventKind
         * @enum {string}
         */
        BenchmarkEventKind: "BENCHMARK_STARTED" | "ARM_STARTED" | "DAY_TICK" | "DECISION_TAKEN" | "ARM_COMPLETED" | "BENCHMARK_COMPLETED" | "BENCHMARK_FAILED";
        /** BenchmarkResult */
        BenchmarkResult: {
            /** Benchmark Id */
            benchmark_id: string;
            config: components["schemas"]["BenchmarkConfig"];
            calibration_window: components["schemas"]["DateWindow"];
            blind_window: components["schemas"]["DateWindow"];
            historical_arm_provenance: components["schemas"]["SeriesProvenance"];
            /** Arms */
            arms: components["schemas"]["ArmResult"][];
            /** Comparisons */
            comparisons: components["schemas"]["ArmComparison"][];
            /** Anchor Comparisons */
            anchor_comparisons: components["schemas"]["AnchorComparison"][];
            /** Fixture Hashes */
            fixture_hashes: {
                [key: string]: string;
            };
            /** Runtime Ms */
            runtime_ms: number;
            /** Notice */
            notice: string;
        };
        /**
         * BenchmarkStage
         * @enum {string}
         */
        BenchmarkStage: "READY" | "RUNNING" | "COMPLETE" | "FAILED";
        /** BenchmarkState */
        BenchmarkState: {
            /** Benchmark Id */
            benchmark_id: string;
            stage: components["schemas"]["BenchmarkStage"];
            config: components["schemas"]["BenchmarkConfig"];
            /** Events */
            events?: components["schemas"]["BenchmarkEvent"][];
            result?: components["schemas"]["BenchmarkResult"] | null;
            /** Playback Notice */
            playback_notice: string;
            /** Error */
            error?: string | null;
        };
        /** BerthPoolConfig */
        BerthPoolConfig: {
            /** Active Berths */
            active_berths: number;
            /** Reserve Tranches */
            reserve_tranches?: components["schemas"]["ReserveBerthTranche"][];
        };
        /** BlindAuditEntry */
        BlindAuditEntry: {
            /** Day Index */
            day_index: number;
            /**
             * Clock
             * Format: date-time
             */
            clock: string;
            /**
             * Requested Until
             * Format: date-time
             */
            requested_until: string;
            /** Lookahead Seconds */
            lookahead_seconds: number;
        };
        /** BlindAuditSummary */
        BlindAuditSummary: {
            /** Total Reads */
            total_reads: number;
            /** Max Lookahead Seconds */
            max_lookahead_seconds: number;
            /** Violations */
            violations: number;
            verdict: components["schemas"]["AuditVerdict"];
            worst_entry?: components["schemas"]["BlindAuditEntry"] | null;
        };
        /** BlockForecast */
        BlockForecast: {
            /** Block Id */
            block_id: string;
            /** Container Capacity */
            container_capacity: number;
            /** Series */
            series: components["schemas"]["YardOccupancyPoint"][];
            /** Peak Occupancy */
            peak_occupancy: number;
            /**
             * Peak Time
             * Format: date-time
             */
            peak_time: string;
        };
        /** CalibrationReport */
        CalibrationReport: {
            window: components["schemas"]["DateWindow"];
            fitted: components["schemas"]["ServiceModelConfig"];
            /** Effective Berths */
            effective_berths: number;
            /** Observed Mean Daily Portcalls */
            observed_mean_daily_portcalls: number;
            /** Simulated Mean Daily Portcalls */
            simulated_mean_daily_portcalls: number;
            /** Throughput Error Pct */
            throughput_error_pct: number;
            /** Simulated Mean Wait Days */
            simulated_mean_wait_days: number;
            /** Simulated Mean Port Stay Hours */
            simulated_mean_port_stay_hours: number;
            /** Erlang C Wait Days */
            erlang_c_wait_days: number;
            /** Utilisation */
            utilisation: number;
            /** Passed */
            passed: boolean;
            /** Notes */
            notes?: string[];
        };
        /**
         * CargoType
         * @enum {string}
         */
        CargoType: "PHARMA_REEFER" | "TIME_CRITICAL_MANUFACTURING" | "GENERAL_DRY";
        /**
         * Confidence
         * @enum {string}
         */
        Confidence: "HIGH" | "MEDIUM" | "LOW";
        /** ConnectionAnalysis */
        ConnectionAnalysis: {
            /** Delay Hours */
            delay_hours: number;
            /** Safe Count */
            safe_count: number;
            /** At Risk Count */
            at_risk_count: number;
            /** Missed Count */
            missed_count: number;
            /** Groups */
            groups: components["schemas"]["ConnectionGroupSummary"][];
            /** Connections */
            connections: components["schemas"]["ContainerConnection"][];
        };
        /** ConnectionGroupSummary */
        ConnectionGroupSummary: {
            /** Onward Vessel */
            onward_vessel: string;
            cargo_type: components["schemas"]["CargoType"];
            status: components["schemas"]["ConnectionStatus"];
            /** Container Count */
            container_count: number;
        };
        /**
         * ConnectionStatus
         * @enum {string}
         */
        ConnectionStatus: "SAFE" | "AT_RISK" | "MISSED" | "RESOLVED";
        /** ContainerConnection */
        ContainerConnection: {
            /** Container Id */
            container_id: string;
            cargo_type: components["schemas"]["CargoType"];
            /** Onward Vessel */
            onward_vessel: string;
            /**
             * Ready Time
             * Format: date-time
             */
            ready_time: string;
            /**
             * Connection Cutoff
             * Format: date-time
             */
            connection_cutoff: string;
            /** Margin Hours */
            margin_hours: number;
            status: components["schemas"]["ConnectionStatus"];
            /** Priority Rank */
            priority_rank: number;
            /** Priority Reason */
            priority_reason: string;
        };
        /** CostComponent */
        CostComponent: {
            /** Name */
            name: string;
            /** Amount */
            amount: number;
            /** Basis */
            basis: string;
        };
        /** CostEstimate */
        CostEstimate: {
            /** Components */
            components: components["schemas"]["CostComponent"][];
            /** Total */
            total: number;
            /**
             * Illustrative
             * @default true
             */
            illustrative: boolean;
        };
        /** CreateBenchmarkRequest */
        CreateBenchmarkRequest: {
            /**
             * Seed
             * @default 42
             */
            seed: number;
            /** Arms */
            arms?: components["schemas"]["FleetArm"][] | null;
            /** @default SCRIPTED */
            brain: components["schemas"]["FleetBrainMode"];
            /**
             * Playback Speed
             * @default 1
             */
            playback_speed: number;
        };
        /**
         * CreateRunRequest
         * @description Scenario controls plus explicit run-mode selection.
         */
        CreateRunRequest: {
            /**
             * Delay Hours
             * @default 18
             */
            delay_hours: number;
            /** @default BALANCED */
            priority_emphasis: components["schemas"]["PriorityEmphasis"];
            /**
             * Alternative Sailing Failure
             * @default true
             */
            alternative_sailing_failure: boolean;
            /** @default LIVE_STUB */
            mode: components["schemas"]["RunMode"];
        };
        /** DailyKpi */
        DailyKpi: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Day Index */
            day_index: number;
            /** Arrivals */
            arrivals: number;
            /** Berthings */
            berthings: number;
            /** Departures */
            departures: number;
            /** Queue Length */
            queue_length: number;
            /** Mean Wait Days */
            mean_wait_days: number;
            /** Rolling Wait Days */
            rolling_wait_days: number;
            /** Active Berths */
            active_berths: number;
            /** Teu Waiting */
            teu_waiting: number;
            /** Utilisation */
            utilisation: number;
        };
        /** DateWindow */
        DateWindow: {
            /** Label */
            label: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
        };
        /**
         * DecisionSource
         * @enum {string}
         */
        DecisionSource: "SCRIPTED" | "MODEL" | "SCRIPTED_FALLBACK";
        /** Dispute */
        Dispute: {
            /** Dispute Id */
            dispute_id: string;
            /** Question */
            question: string;
            /** Positions */
            positions: components["schemas"]["DisputePosition"][];
            /** Confirmed Constraint */
            confirmed_constraint?: string | null;
            /**
             * Resolved By Human
             * @default false
             */
            resolved_by_human: boolean;
        };
        /** DisputePosition */
        DisputePosition: {
            agent: components["schemas"]["AgentName"];
            /** Position */
            position: string;
            /** Evidence */
            evidence: string[];
        };
        /** DisputeResolutionRequest */
        DisputeResolutionRequest: {
            /** Dispute Id */
            dispute_id: string;
            /** Confirmed Constraint */
            confirmed_constraint: string;
        };
        /** DisruptionAlert */
        DisruptionAlert: {
            /** Vessel Name */
            vessel_name: string;
            /** Port Call */
            port_call: string;
            /**
             * Original Eta
             * Format: date-time
             */
            original_eta: string;
            /**
             * Revised Eta
             * Format: date-time
             */
            revised_eta: string;
            /**
             * Event Time
             * Format: date-time
             */
            event_time: string;
            /**
             * Synthetic
             * @default true
             */
            synthetic: boolean;
            /** Delay Hours */
            readonly delay_hours: number;
        };
        /**
         * EventKind
         * @enum {string}
         */
        EventKind: "RUN_STARTED" | "AGENT_STARTED" | "TOOL_CALLED" | "AGENT_COMPLETED" | "HANDOFF" | "DISPUTE_OPENED" | "HUMAN_DECISION" | "APPROVAL_REQUIRED" | "ACTION_DISPATCHED" | "ERROR" | "RUN_COMPLETED";
        /**
         * FleetArm
         * @description One line on the benchmark chart.
         * @enum {string}
         */
        FleetArm: "HISTORICAL" | "REACTIVE_BASELINE" | "CASCADE_AGENTIC" | "CASCADE_NO_EXTRA_CAPACITY";
        /**
         * FleetBrainMode
         * @description Which brain supplies weekly strategy. SCRIPTED is the scored default.
         * @enum {string}
         */
        FleetBrainMode: "SCRIPTED" | "LIVE_GEMINI" | "LIVE_CLAUDE";
        /**
         * FleetDecision
         * @description One lever pull. Numeric effect is fixed by the engine, never by a model.
         */
        FleetDecision: {
            type: components["schemas"]["FleetDecisionType"];
            /** Tranche Id */
            tranche_id?: string | null;
            discipline?: components["schemas"]["QueueDiscipline"] | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Surge Level */
            surge_level?: number | null;
            /** Rationale */
            rationale: string;
        };
        /**
         * FleetDecisionType
         * @enum {string}
         */
        FleetDecisionType: "ACTIVATE_RESERVE_BERTHS" | "SET_QUEUE_DISCIPLINE" | "FAST_CONNECTION_MODE" | "WORKFORCE_SURGE" | "HOLD";
        /** FleetMetrics */
        FleetMetrics: {
            /** Peak Wait Days */
            peak_wait_days: number;
            /**
             * Peak Wait Date
             * Format: date
             */
            peak_wait_date: string;
            /** Recovery Date */
            recovery_date?: string | null;
            /** Days Above Two Day Wait */
            days_above_two_day_wait: number;
            /** Mean Wait Days */
            mean_wait_days: number;
            /** Mean Port Stay Hours */
            mean_port_stay_hours: number;
            /** Port Stay Inflation Pct */
            port_stay_inflation_pct: number;
            /** Vessels Served */
            vessels_served: number;
            /** Teu Served */
            teu_served: number;
            /** Missed Connection Proxy */
            missed_connection_proxy: number;
            /** Wait Cost Usd */
            wait_cost_usd: number;
        };
        /**
         * FleetWorldConfig
         * @description Parallel to WorldFixture, for the fleet scale. Never replaces it.
         */
        FleetWorldConfig: {
            /** Seed */
            seed: number;
            berths: components["schemas"]["BerthPoolConfig"];
            service: components["schemas"]["ServiceModelConfig"];
            /**
             * Arrival Jitter Hours
             * @default 0
             */
            arrival_jitter_hours: number;
            /**
             * Service Rate Multiplier
             * @default 1
             */
            service_rate_multiplier: number;
            /**
             * Berth Delta
             * @default 0
             */
            berth_delta: number;
            /** Activation Lead Override Days */
            activation_lead_override_days?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** MockedAction */
        MockedAction: {
            /** Action Id */
            action_id: string;
            action_type: components["schemas"]["MockedActionType"];
            plan_archetype: components["schemas"]["PlanArchetype"];
            /** Description */
            description: string;
            /** Payload Summary */
            payload_summary: string;
        };
        /**
         * MockedActionType
         * @enum {string}
         */
        MockedActionType: "TERMINAL_WORK_ORDER" | "REEFER_CHECK" | "CARRIER_NOTICE";
        /**
         * ModelExchange
         * @description One live model call (prompt in, raw response out) behind a trace event.
         */
        ModelExchange: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Effort */
            effort?: string | null;
            agent: components["schemas"]["AgentName"];
            /** Prompt */
            prompt: string;
            /** Response */
            response: string;
            /** Duration Ms */
            duration_ms?: number | null;
        };
        /** PlanAction */
        PlanAction: {
            action: components["schemas"]["RecoveryActionType"];
            /** Onward Vessel */
            onward_vessel: string;
            cargo_type: components["schemas"]["CargoType"];
            /** Container Count */
            container_count: number;
            /** Target Sailing */
            target_sailing?: string | null;
            /** Rationale */
            rationale: string;
        };
        /**
         * PlanArchetype
         * @enum {string}
         */
        PlanArchetype: "AGGRESSIVE_RUSH" | "STANDARD_REBOOK" | "OPTIMIZED_HYBRID";
        /** PlanComparison */
        PlanComparison: {
            /** Evaluations */
            evaluations: components["schemas"]["PlanEvaluation"][];
            recommended?: components["schemas"]["PlanArchetype"] | null;
            /** Rationale */
            rationale: string;
            confidence: components["schemas"]["Confidence"];
        };
        /** PlanEvaluation */
        PlanEvaluation: {
            plan: components["schemas"]["RecoveryPlan"];
            metrics: components["schemas"]["PlanMetrics"];
            /** Feasible */
            feasible: boolean;
            /** Rejection Reasons */
            rejection_reasons?: string[];
        };
        /** PlanMetrics */
        PlanMetrics: {
            cost: components["schemas"]["CostEstimate"];
            /** Missed Connections */
            missed_connections: number;
            /** Critical Cargo Protected Pct */
            critical_cargo_protected_pct: number;
            /** Yard Peak Occupancy Pct */
            yard_peak_occupancy_pct: number;
            /** Max Additional Delay Hours */
            max_additional_delay_hours: number;
        };
        /**
         * PriorityEmphasis
         * @enum {string}
         */
        PriorityEmphasis: "CARGO_PROTECTION" | "CONGESTION_REDUCTION" | "BALANCED";
        /**
         * QueueDiscipline
         * @enum {string}
         */
        QueueDiscipline: "FCFS" | "CONNECTION_WEIGHTED" | "PRIORITY_DISCHARGE";
        /** RecordedDecision */
        RecordedDecision: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Day Index */
            day_index: number;
            agent: components["schemas"]["AgentName"];
            decision: components["schemas"]["FleetDecision"];
            /** Accepted */
            accepted: boolean;
            /** Rejection Reason */
            rejection_reason?: string | null;
            source: components["schemas"]["DecisionSource"];
            /** Effective Date */
            effective_date?: string | null;
        };
        /**
         * RecoveryActionType
         * @enum {string}
         */
        RecoveryActionType: "RUSH" | "REBOOK" | "HOLD";
        /** RecoveryPlan */
        RecoveryPlan: {
            archetype: components["schemas"]["PlanArchetype"];
            /** Title */
            title: string;
            /** Actions */
            actions: components["schemas"]["PlanAction"][];
            /** Assumptions */
            assumptions?: string[];
        };
        /** ReeferShortage */
        ReeferShortage: {
            /** Block Id */
            block_id: string;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /** Required Plugs */
            required_plugs: number;
            /** Available Plugs */
            available_plugs: number;
        };
        /** ReserveBerthTranche */
        ReserveBerthTranche: {
            /** Tranche Id */
            tranche_id: string;
            /** Label */
            label: string;
            /** Berths */
            berths: number;
            /** Activation Lead Days */
            activation_lead_days: number;
            /** Available From */
            available_from?: string | null;
            /** Basis */
            basis: string;
        };
        /** RunCreated */
        RunCreated: {
            /** Run Id */
            run_id: string;
            mode: components["schemas"]["RunMode"];
            stage: components["schemas"]["WorkflowStage"];
            /** Events Url */
            events_url: string;
        };
        /**
         * RunMode
         * @enum {string}
         */
        RunMode: "LIVE_STUB" | "LIVE_GEMINI" | "LIVE_CLAUDE" | "DEMO_REPLAY";
        /** RunResults */
        RunResults: {
            connection_analysis?: components["schemas"]["ConnectionAnalysis"] | null;
            baseline_yard?: components["schemas"]["YardForecast"] | null;
            planned_yard?: components["schemas"]["YardForecast"] | null;
            alternative_sailings?: components["schemas"]["AlternativeSailingResult"] | null;
            plan_comparison?: components["schemas"]["PlanComparison"] | null;
            /** Dispatched Actions */
            dispatched_actions?: components["schemas"]["MockedAction"][];
            /** Receipts */
            receipts?: components["schemas"]["ActionReceipt"][];
        };
        /**
         * SailingLookupStatus
         * @enum {string}
         */
        SailingLookupStatus: "MOCK_SUCCESS" | "TIMEOUT_CACHED_FALLBACK";
        /** ScenarioControls */
        ScenarioControls: {
            /**
             * Delay Hours
             * @default 18
             */
            delay_hours: number;
            /** @default BALANCED */
            priority_emphasis: components["schemas"]["PriorityEmphasis"];
            /**
             * Alternative Sailing Failure
             * @default true
             */
            alternative_sailing_failure: boolean;
        };
        /** ScenarioState */
        ScenarioState: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            alert: components["schemas"]["DisruptionAlert"];
            /** Objective */
            objective: string;
            /** Planning Horizon Hours */
            planning_horizon_hours: number;
            controls: components["schemas"]["ScenarioControls"];
            /** Synthetic Notice */
            synthetic_notice: string;
        };
        /**
         * SeriesProvenance
         * @description How a displayed number came to exist. Never inferred, always carried.
         * @enum {string}
         */
        SeriesProvenance: "RECORDED" | "RECONSTRUCTED" | "SIMULATED";
        /**
         * ServiceModelConfig
         * @description Vessel service time model. Fitted on the calibration window only.
         */
        ServiceModelConfig: {
            /** Base Hours */
            base_hours: number;
            /** Cranes Per Berth */
            cranes_per_berth: number;
            /** Moves Per Crane Hour */
            moves_per_crane_hour: number;
            /** Teu Per Move */
            teu_per_move: number;
            /** Efficiency */
            efficiency: number;
            /** Congestion Alpha */
            congestion_alpha: number;
            /** Congestion Queue Ref */
            congestion_queue_ref: number;
            /** Congestion Cap */
            congestion_cap: number;
            /** Surge Alpha Factor */
            surge_alpha_factor: number;
            /** Surge Efficiency Gain */
            surge_efficiency_gain: number;
            /** Fast Connection Speedup */
            fast_connection_speedup: number;
        };
        /** TraceEvent */
        TraceEvent: {
            /** Event Id */
            event_id: string;
            /** Sequence */
            sequence: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            kind: components["schemas"]["EventKind"];
            stage: components["schemas"]["WorkflowStage"];
            agent?: components["schemas"]["AgentName"] | null;
            /** Objective */
            objective?: string | null;
            /** Input Summary */
            input_summary?: string | null;
            /** Tool */
            tool?: string | null;
            /** Decision Summary */
            decision_summary?: string | null;
            confidence?: components["schemas"]["Confidence"] | null;
            /** Assumptions */
            assumptions?: string[];
            /** Result */
            result?: string | null;
            /** Error */
            error?: string | null;
            /** Elapsed Ms */
            elapsed_ms?: number | null;
            next_handoff?: components["schemas"]["AgentName"] | null;
            /** Parallel Group */
            parallel_group?: string | null;
            /** Model Exchanges */
            model_exchanges?: components["schemas"]["ModelExchange"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkflowStage
         * @enum {string}
         */
        WorkflowStage: "READY" | "ASSESSING" | "DISPUTE" | "PLANNING" | "AWAITING_APPROVAL" | "EXECUTING" | "COMPLETE" | "FAILED";
        /** WorkflowState */
        WorkflowState: {
            /** Run Id */
            run_id: string;
            mode: components["schemas"]["RunMode"];
            stage: components["schemas"]["WorkflowStage"];
            scenario: components["schemas"]["ScenarioState"];
            /** Activities */
            activities: components["schemas"]["AgentActivity"][];
            /** Trace */
            trace?: components["schemas"]["TraceEvent"][];
            active_dispute?: components["schemas"]["Dispute"] | null;
            results?: components["schemas"]["RunResults"] | null;
        };
        /** YardForecast */
        YardForecast: {
            /** Horizon Hours */
            horizon_hours: number;
            /** Blocks */
            blocks: components["schemas"]["BlockForecast"][];
            /** Reefer Shortages */
            reefer_shortages: components["schemas"]["ReeferShortage"][];
        };
        /** YardOccupancyPoint */
        YardOccupancyPoint: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Occupancy */
            occupancy: number;
            /** Congested */
            congested: boolean;
            /** Full */
            full: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_scenario_api_scenario_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioState"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: {
                /** @description Overrides the body mode field. */
                mode?: components["schemas"]["RunMode"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_dispute_api_runs__run_id__dispute_resolution_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisputeResolutionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_approval_api_runs__run_id__approval_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_benchmark_api_benchmarks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBenchmarkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_benchmark_api_benchmarks__benchmark_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                benchmark_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_benchmark_api_benchmarks__benchmark_id__get: {
        parameters: {
            query?: {
                /** @description Skip events already received over SSE. */
                since?: number;
            };
            header?: never;
            path: {
                benchmark_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_demo_api_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioState"];
                };
            };
        };
    };
}
