import type { components } from './schema'

export type ScenarioState = components['schemas']['ScenarioState']
export type ScenarioControls = components['schemas']['ScenarioControls']
export type PriorityEmphasis = components['schemas']['PriorityEmphasis']
export type TraceEvent = components['schemas']['TraceEvent']
export type RunCreated = components['schemas']['RunCreated']
export type AgentName = components['schemas']['AgentName']
export type AgentActivity = components['schemas']['AgentActivity']
export type AgentStatus = components['schemas']['AgentStatus']
export type WorkflowState = components['schemas']['WorkflowState']
export type WorkflowStage = components['schemas']['WorkflowStage']
export type RunMode = components['schemas']['RunMode']
export type RunResults = components['schemas']['RunResults']
export type ConnectionAnalysis = components['schemas']['ConnectionAnalysis']
export type ConnectionGroupSummary = components['schemas']['ConnectionGroupSummary']
export type ConnectionStatus = components['schemas']['ConnectionStatus']
export type CargoType = components['schemas']['CargoType']
export type YardForecast = components['schemas']['YardForecast']
export type BlockForecast = components['schemas']['BlockForecast']
export type ReeferShortage = components['schemas']['ReeferShortage']
export type PlanComparison = components['schemas']['PlanComparison']
export type AlternativeSailingResult = components['schemas']['AlternativeSailingResult']
export type PlanEvaluation = components['schemas']['PlanEvaluation']
export type PlanArchetype = components['schemas']['PlanArchetype']
export type MockedAction = components['schemas']['MockedAction']
export type ActionReceipt = components['schemas']['ActionReceipt']
export type Dispute = components['schemas']['Dispute']
export type Confidence = components['schemas']['Confidence']
export type EventKind = components['schemas']['EventKind']

export type ModelExchange = components['schemas']['ModelExchange']

// Act 2: the Red Sea 2024 crisis benchmark. A parallel contract family; none of
// the types above change shape because of it.
export type FleetArm = components['schemas']['FleetArm']
export type SeriesProvenance = components['schemas']['SeriesProvenance']
export type DailyKpi = components['schemas']['DailyKpi']
export type FleetMetrics = components['schemas']['FleetMetrics']
export type FleetDecision = components['schemas']['FleetDecision']
export type RecordedDecision = components['schemas']['RecordedDecision']
export type BlindAuditSummary = components['schemas']['BlindAuditSummary']
export type ArmResult = components['schemas']['ArmResult']
export type ArmComparison = components['schemas']['ArmComparison']
export type AnchorComparison = components['schemas']['AnchorComparison']
export type BenchmarkResult = components['schemas']['BenchmarkResult']
export type BenchmarkStage = components['schemas']['BenchmarkStage']
export type BenchmarkState = components['schemas']['BenchmarkState']
export type BenchmarkEvent = components['schemas']['BenchmarkEvent']
export type BenchmarkEventKind = components['schemas']['BenchmarkEventKind']
export type BenchmarkCreated = components['schemas']['BenchmarkCreated']
export type CreateBenchmarkRequest = components['schemas']['CreateBenchmarkRequest']

export type DisputeResolutionRequest = components['schemas']['DisputeResolutionRequest']
export type ApprovalDecision = components['schemas']['ApprovalDecision']
export type ApprovalRequest = components['schemas']['ApprovalRequest']
