/**
 * Generated by scripts/export_scenario_preview.py. Do not edit by hand.
 *
 * What the deterministic engine produces for every scenario control the UI can
 * set, so the Command Center's pre-run preview is the run's own answer shown
 * early rather than a hand-written guess that the run then contradicts.
 */
import type { PriorityEmphasis } from '../api/types'

export interface ScenarioPreview {
  /** Transshipment containers with an onward connection off the delayed vessel. */
  affected: number
  safe: number
  atRisk: number
  missed: number
  /** Highest block occupancy over the planning horizon, as a percent of capacity. */
  yardPeak: number
  reeferDemand: number
  reeferCapacity: number
  cargo: Record<string, number>
  blocks: Array<{ id: string; peak: number }>
}

const PREVIEWS: Record<string, ScenarioPreview> = {
  "6:CARGO_PROTECTION": {
    "affected": 360,
    "safe": 334,
    "atRisk": 26,
    "missed": 0,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "6:CONGESTION_REDUCTION": {
    "affected": 360,
    "safe": 334,
    "atRisk": 26,
    "missed": 0,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "6:BALANCED": {
    "affected": 360,
    "safe": 334,
    "atRisk": 26,
    "missed": 0,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "7:CARGO_PROTECTION": {
    "affected": 360,
    "safe": 326,
    "atRisk": 34,
    "missed": 0,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "7:CONGESTION_REDUCTION": {
    "affected": 360,
    "safe": 326,
    "atRisk": 34,
    "missed": 0,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "7:BALANCED": {
    "affected": 360,
    "safe": 326,
    "atRisk": 34,
    "missed": 0,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "8:CARGO_PROTECTION": {
    "affected": 360,
    "safe": 323,
    "atRisk": 37,
    "missed": 0,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "8:CONGESTION_REDUCTION": {
    "affected": 360,
    "safe": 323,
    "atRisk": 37,
    "missed": 0,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "8:BALANCED": {
    "affected": 360,
    "safe": 323,
    "atRisk": 37,
    "missed": 0,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "9:CARGO_PROTECTION": {
    "affected": 360,
    "safe": 315,
    "atRisk": 39,
    "missed": 6,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "9:CONGESTION_REDUCTION": {
    "affected": 360,
    "safe": 315,
    "atRisk": 39,
    "missed": 6,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "9:BALANCED": {
    "affected": 360,
    "safe": 315,
    "atRisk": 39,
    "missed": 6,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "10:CARGO_PROTECTION": {
    "affected": 360,
    "safe": 304,
    "atRisk": 38,
    "missed": 18,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "10:CONGESTION_REDUCTION": {
    "affected": 360,
    "safe": 304,
    "atRisk": 38,
    "missed": 18,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "10:BALANCED": {
    "affected": 360,
    "safe": 304,
    "atRisk": 38,
    "missed": 18,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "11:CARGO_PROTECTION": {
    "affected": 360,
    "safe": 294,
    "atRisk": 40,
    "missed": 26,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "11:CONGESTION_REDUCTION": {
    "affected": 360,
    "safe": 294,
    "atRisk": 40,
    "missed": 26,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "11:BALANCED": {
    "affected": 360,
    "safe": 294,
    "atRisk": 40,
    "missed": 26,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "12:CARGO_PROTECTION": {
    "affected": 360,
    "safe": 279,
    "atRisk": 47,
    "missed": 34,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "12:CONGESTION_REDUCTION": {
    "affected": 360,
    "safe": 279,
    "atRisk": 47,
    "missed": 34,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "12:BALANCED": {
    "affected": 360,
    "safe": 279,
    "atRisk": 47,
    "missed": 34,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "13:CARGO_PROTECTION": {
    "affected": 360,
    "safe": 258,
    "atRisk": 65,
    "missed": 37,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "13:CONGESTION_REDUCTION": {
    "affected": 360,
    "safe": 258,
    "atRisk": 65,
    "missed": 37,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "13:BALANCED": {
    "affected": 360,
    "safe": 258,
    "atRisk": 65,
    "missed": 37,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "14:CARGO_PROTECTION": {
    "affected": 360,
    "safe": 241,
    "atRisk": 74,
    "missed": 45,
    "yardPeak": 84,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 83
      },
      {
        "id": "YB2",
        "peak": 83
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 78
      }
    ]
  },
  "14:CONGESTION_REDUCTION": {
    "affected": 360,
    "safe": 241,
    "atRisk": 74,
    "missed": 45,
    "yardPeak": 84,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 83
      },
      {
        "id": "YB2",
        "peak": 83
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 78
      }
    ]
  },
  "14:BALANCED": {
    "affected": 360,
    "safe": 241,
    "atRisk": 74,
    "missed": 45,
    "yardPeak": 84,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 83
      },
      {
        "id": "YB2",
        "peak": 83
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 78
      }
    ]
  },
  "15:CARGO_PROTECTION": {
    "affected": 360,
    "safe": 223,
    "atRisk": 81,
    "missed": 56,
    "yardPeak": 83,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 83
      },
      {
        "id": "YB2",
        "peak": 83
      },
      {
        "id": "YB3",
        "peak": 82
      },
      {
        "id": "YB4",
        "peak": 79
      }
    ]
  },
  "15:CONGESTION_REDUCTION": {
    "affected": 360,
    "safe": 223,
    "atRisk": 81,
    "missed": 56,
    "yardPeak": 83,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 83
      },
      {
        "id": "YB2",
        "peak": 83
      },
      {
        "id": "YB3",
        "peak": 82
      },
      {
        "id": "YB4",
        "peak": 79
      }
    ]
  },
  "15:BALANCED": {
    "affected": 360,
    "safe": 223,
    "atRisk": 81,
    "missed": 56,
    "yardPeak": 83,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 83
      },
      {
        "id": "YB2",
        "peak": 83
      },
      {
        "id": "YB3",
        "peak": 82
      },
      {
        "id": "YB4",
        "peak": 79
      }
    ]
  },
  "16:CARGO_PROTECTION": {
    "affected": 360,
    "safe": 211,
    "atRisk": 83,
    "missed": 66,
    "yardPeak": 84,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 84
      },
      {
        "id": "YB2",
        "peak": 83
      },
      {
        "id": "YB3",
        "peak": 81
      },
      {
        "id": "YB4",
        "peak": 79
      }
    ]
  },
  "16:CONGESTION_REDUCTION": {
    "affected": 360,
    "safe": 211,
    "atRisk": 83,
    "missed": 66,
    "yardPeak": 84,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 84
      },
      {
        "id": "YB2",
        "peak": 83
      },
      {
        "id": "YB3",
        "peak": 81
      },
      {
        "id": "YB4",
        "peak": 79
      }
    ]
  },
  "16:BALANCED": {
    "affected": 360,
    "safe": 211,
    "atRisk": 83,
    "missed": 66,
    "yardPeak": 84,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 84
      },
      {
        "id": "YB2",
        "peak": 83
      },
      {
        "id": "YB3",
        "peak": 81
      },
      {
        "id": "YB4",
        "peak": 79
      }
    ]
  },
  "17:CARGO_PROTECTION": {
    "affected": 360,
    "safe": 202,
    "atRisk": 77,
    "missed": 81,
    "yardPeak": 84,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 84
      },
      {
        "id": "YB2",
        "peak": 84
      },
      {
        "id": "YB3",
        "peak": 81
      },
      {
        "id": "YB4",
        "peak": 79
      }
    ]
  },
  "17:CONGESTION_REDUCTION": {
    "affected": 360,
    "safe": 202,
    "atRisk": 77,
    "missed": 81,
    "yardPeak": 84,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 84
      },
      {
        "id": "YB2",
        "peak": 84
      },
      {
        "id": "YB3",
        "peak": 81
      },
      {
        "id": "YB4",
        "peak": 79
      }
    ]
  },
  "17:BALANCED": {
    "affected": 360,
    "safe": 202,
    "atRisk": 77,
    "missed": 81,
    "yardPeak": 84,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 84
      },
      {
        "id": "YB2",
        "peak": 84
      },
      {
        "id": "YB3",
        "peak": 81
      },
      {
        "id": "YB4",
        "peak": 79
      }
    ]
  },
  "18:CARGO_PROTECTION": {
    "affected": 360,
    "safe": 188,
    "atRisk": 70,
    "missed": 102,
    "yardPeak": 85,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 84
      },
      {
        "id": "YB2",
        "peak": 85
      },
      {
        "id": "YB3",
        "peak": 82
      },
      {
        "id": "YB4",
        "peak": 79
      }
    ]
  },
  "18:CONGESTION_REDUCTION": {
    "affected": 360,
    "safe": 188,
    "atRisk": 70,
    "missed": 102,
    "yardPeak": 85,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 84
      },
      {
        "id": "YB2",
        "peak": 85
      },
      {
        "id": "YB3",
        "peak": 82
      },
      {
        "id": "YB4",
        "peak": 79
      }
    ]
  },
  "18:BALANCED": {
    "affected": 360,
    "safe": 188,
    "atRisk": 70,
    "missed": 102,
    "yardPeak": 85,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 84
      },
      {
        "id": "YB2",
        "peak": 85
      },
      {
        "id": "YB3",
        "peak": 82
      },
      {
        "id": "YB4",
        "peak": 79
      }
    ]
  },
  "19:CARGO_PROTECTION": {
    "affected": 360,
    "safe": 176,
    "atRisk": 65,
    "missed": 119,
    "yardPeak": 85,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 85
      },
      {
        "id": "YB3",
        "peak": 83
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "19:CONGESTION_REDUCTION": {
    "affected": 360,
    "safe": 176,
    "atRisk": 65,
    "missed": 119,
    "yardPeak": 85,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 85
      },
      {
        "id": "YB3",
        "peak": 83
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "19:BALANCED": {
    "affected": 360,
    "safe": 176,
    "atRisk": 65,
    "missed": 119,
    "yardPeak": 85,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 85
      },
      {
        "id": "YB3",
        "peak": 83
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "20:CARGO_PROTECTION": {
    "affected": 360,
    "safe": 153,
    "atRisk": 70,
    "missed": 137,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "20:CONGESTION_REDUCTION": {
    "affected": 360,
    "safe": 153,
    "atRisk": 70,
    "missed": 137,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "20:BALANCED": {
    "affected": 360,
    "safe": 153,
    "atRisk": 70,
    "missed": 137,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "21:CARGO_PROTECTION": {
    "affected": 360,
    "safe": 130,
    "atRisk": 81,
    "missed": 149,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "21:CONGESTION_REDUCTION": {
    "affected": 360,
    "safe": 130,
    "atRisk": 81,
    "missed": 149,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "21:BALANCED": {
    "affected": 360,
    "safe": 130,
    "atRisk": 81,
    "missed": 149,
    "yardPeak": 86,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 85
      },
      {
        "id": "YB2",
        "peak": 86
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 80
      }
    ]
  },
  "22:CARGO_PROTECTION": {
    "affected": 360,
    "safe": 111,
    "atRisk": 91,
    "missed": 158,
    "yardPeak": 84,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 83
      },
      {
        "id": "YB2",
        "peak": 83
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 78
      }
    ]
  },
  "22:CONGESTION_REDUCTION": {
    "affected": 360,
    "safe": 111,
    "atRisk": 91,
    "missed": 158,
    "yardPeak": 84,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 83
      },
      {
        "id": "YB2",
        "peak": 83
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 78
      }
    ]
  },
  "22:BALANCED": {
    "affected": 360,
    "safe": 111,
    "atRisk": 91,
    "missed": 158,
    "yardPeak": 84,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 83
      },
      {
        "id": "YB2",
        "peak": 83
      },
      {
        "id": "YB3",
        "peak": 84
      },
      {
        "id": "YB4",
        "peak": 78
      }
    ]
  },
  "23:CARGO_PROTECTION": {
    "affected": 360,
    "safe": 95,
    "atRisk": 93,
    "missed": 172,
    "yardPeak": 83,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 82
      },
      {
        "id": "YB2",
        "peak": 83
      },
      {
        "id": "YB3",
        "peak": 82
      },
      {
        "id": "YB4",
        "peak": 78
      }
    ]
  },
  "23:CONGESTION_REDUCTION": {
    "affected": 360,
    "safe": 95,
    "atRisk": 93,
    "missed": 172,
    "yardPeak": 83,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 82
      },
      {
        "id": "YB2",
        "peak": 83
      },
      {
        "id": "YB3",
        "peak": 82
      },
      {
        "id": "YB4",
        "peak": 78
      }
    ]
  },
  "23:BALANCED": {
    "affected": 360,
    "safe": 95,
    "atRisk": 93,
    "missed": 172,
    "yardPeak": 83,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 82
      },
      {
        "id": "YB2",
        "peak": 83
      },
      {
        "id": "YB3",
        "peak": 82
      },
      {
        "id": "YB4",
        "peak": 78
      }
    ]
  },
  "24:CARGO_PROTECTION": {
    "affected": 360,
    "safe": 87,
    "atRisk": 89,
    "missed": 184,
    "yardPeak": 83,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 83
      },
      {
        "id": "YB2",
        "peak": 83
      },
      {
        "id": "YB3",
        "peak": 82
      },
      {
        "id": "YB4",
        "peak": 78
      }
    ]
  },
  "24:CONGESTION_REDUCTION": {
    "affected": 360,
    "safe": 87,
    "atRisk": 89,
    "missed": 184,
    "yardPeak": 83,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 83
      },
      {
        "id": "YB2",
        "peak": 83
      },
      {
        "id": "YB3",
        "peak": 82
      },
      {
        "id": "YB4",
        "peak": 78
      }
    ]
  },
  "24:BALANCED": {
    "affected": 360,
    "safe": 87,
    "atRisk": 89,
    "missed": 184,
    "yardPeak": 83,
    "reeferDemand": 21,
    "reeferCapacity": 18,
    "cargo": {
      "PHARMA_REEFER": 60,
      "TIME_CRITICAL_MANUFACTURING": 130,
      "GENERAL_DRY": 170
    },
    "blocks": [
      {
        "id": "YB1",
        "peak": 83
      },
      {
        "id": "YB2",
        "peak": 83
      },
      {
        "id": "YB3",
        "peak": 82
      },
      {
        "id": "YB4",
        "peak": 78
      }
    ]
  }
}

/** The table covers the whole ScenarioControls space, so this never misses. */
export function scenarioPreview(
  delayHours: number,
  emphasis: PriorityEmphasis,
): ScenarioPreview {
  const clamped = Math.min(24, Math.max(6, Math.round(delayHours)))
  return PREVIEWS[`${clamped}:${emphasis}`]
}
