"""Generate the Command Center's pre-run preview from the real engine.

Before a run starts there is no analysis to show, so the Command Center shows a
preview of what the configured scenario is expected to produce. Those figures
used to be hand-written constants in ``frontend/src/data/demo.ts``, and they did
not match: the preview promised 400 affected containers, 126 at risk and a 94%
yard peak, then the run replaced them with 360, 70 and 85%. An operator reading
the panel could not tell which set was real, and the slider moved neither.

This computes the preview with the same two engine calls the run itself makes -
``analyse_connections`` then ``simulate_yard`` - for every control combination
the UI can produce (``ScenarioControls`` bounds the delay to 6..24 hours and the
emphasis to three values, so the table is total: 57 rows, no gaps and no
extrapolation). The preview is then the run's own answer, shown early.

``alternative_sailing_failure`` is deliberately not a key. It only degrades the
onward-sailing lookup during planning; the assessment the preview shows is
identical either way.

Regenerate with::

    uv run python scripts/export_scenario_preview.py
"""

import json
from pathlib import Path
from typing import Any

from cascade.contracts import (
    CargoType,
    ConnectionAnalysis,
    PriorityEmphasis,
    ScenarioControls,
    YardForecast,
)
from cascade.tools.engine_toolbox import EngineToolBox
from cascade.tools.toolbox import build_toolbox
from cascade.workflow import scenario_with_controls

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "frontend" / "src" / "data" / "scenarioPreview.generated.ts"

DELAY_RANGE = range(6, 25)


def _yard_peak_pct(yard: YardForecast) -> int:
    peak = 0.0
    for block in yard.blocks:
        if block.container_capacity <= 0:
            continue
        peak = max(peak, block.peak_occupancy / block.container_capacity * 100)
    return round(peak)


def _preview(delay_hours: int, emphasis: PriorityEmphasis) -> dict[str, Any]:
    controls = ScenarioControls(delay_hours=delay_hours, priority_emphasis=emphasis)
    scenario = scenario_with_controls(controls)
    toolbox = build_toolbox()
    # A silent fallback to FakeToolBox would publish figures the run never produces.
    assert isinstance(toolbox, EngineToolBox)
    analysis: ConnectionAnalysis = toolbox.analyse_connections(scenario.alert.revised_eta, emphasis)
    yard = toolbox.simulate_yard(
        scenario.alert.revised_eta, analysis, None, scenario.planning_horizon_hours
    )
    shortage = yard.reefer_shortages[0] if yard.reefer_shortages else None
    cargo = dict.fromkeys((cargo_type.value for cargo_type in CargoType), 0)
    for group in analysis.groups:
        cargo[group.cargo_type.value] += group.container_count
    return {
        "affected": sum(group.container_count for group in analysis.groups),
        "safe": analysis.safe_count,
        "atRisk": analysis.at_risk_count,
        "missed": analysis.missed_count,
        "yardPeak": _yard_peak_pct(yard),
        "reeferDemand": shortage.required_plugs if shortage else 0,
        "reeferCapacity": shortage.available_plugs if shortage else 0,
        "cargo": cargo,
        "blocks": [
            {
                "id": block.block_id,
                "peak": (
                    round(block.peak_occupancy / block.container_capacity * 100)
                    if block.container_capacity > 0
                    else 0
                ),
            }
            for block in yard.blocks
        ],
    }


def build_table() -> dict[str, dict[str, Any]]:
    return {
        f"{delay}:{emphasis.value}": _preview(delay, emphasis)
        for delay in DELAY_RANGE
        for emphasis in PriorityEmphasis
    }


def render(table: dict[str, dict[str, Any]]) -> str:
    body = json.dumps(table, indent=2)
    return f"""/**
 * Generated by scripts/export_scenario_preview.py. Do not edit by hand.
 *
 * What the deterministic engine produces for every scenario control the UI can
 * set, so the Command Center's pre-run preview is the run's own answer shown
 * early rather than a hand-written guess that the run then contradicts.
 */
import type {{ PriorityEmphasis }} from '../api/types'

export interface ScenarioPreview {{
  /** Transshipment containers with an onward connection off the delayed vessel. */
  affected: number
  safe: number
  atRisk: number
  missed: number
  /** Highest block occupancy over the planning horizon, as a percent of capacity. */
  yardPeak: number
  reeferDemand: number
  reeferCapacity: number
  cargo: Record<string, number>
  blocks: Array<{{ id: string; peak: number }}>
}}

const PREVIEWS: Record<string, ScenarioPreview> = {body}

/** The table covers the whole ScenarioControls space, so this never misses. */
export function scenarioPreview(
  delayHours: number,
  emphasis: PriorityEmphasis,
): ScenarioPreview {{
  const clamped = Math.min(24, Math.max(6, Math.round(delayHours)))
  return PREVIEWS[`${{clamped}}:${{emphasis}}`]
}}
"""


def main() -> None:
    OUTPUT_PATH.write_text(render(build_table()), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
