"""Record one real Act 1 run as the shared agent-status contract.

The backend derives per-agent status in ``WorkflowRun.activities()`` and the
frontend derives it again in ``frontend/src/lib/derive.ts``, from the same
trace. Two machines, two languages, one answer required: a viewer looking at an
agent badge cannot tell which of them produced it, so a disagreement shows up
as the UI contradicting itself.

This writes ``fixtures/agent_status_golden.json``: the trace of a full golden
run reduced to the fields the status machines actually read, plus the status
the backend ends on for every agent. ``tests/test_agent_status_golden.py``
asserts the file still matches a fresh run, and
``frontend/src/lib/derive.test.ts`` replays the same trace through the frontend
and asserts it lands on the same statuses.

Regenerate with::

    uv run python scripts/export_agent_status_golden.py
"""

import asyncio
import json
from collections.abc import Callable
from pathlib import Path
from typing import Any

from cascade.agents.scripted import ScriptedBrain
from cascade.contracts import (
    ApprovalDecision,
    ApprovalRequest,
    DisputeResolutionRequest,
    RunMode,
    ScenarioControls,
    WorkflowStage,
)
from cascade.tools.engine_toolbox import EngineToolBox
from cascade.tools.toolbox import build_toolbox
from cascade.workflow import WorkflowRun, scenario_with_controls

CONSTRAINT = "Respect physical reefer plug capacity"
GOLDEN_PATH = Path(__file__).resolve().parents[1] / "fixtures" / "agent_status_golden.json"


async def _wait_for(predicate: Callable[[], bool], timeout: float = 30.0) -> None:
    async def poll() -> None:
        while not predicate():
            await asyncio.sleep(0.005)

    await asyncio.wait_for(poll(), timeout)


async def record_golden_run() -> dict[str, Any]:
    """Drive the default demo path to COMPLETE and reduce it to the contract."""
    toolbox = build_toolbox()
    # A silent fallback to FakeToolBox would record a trace the app never shows.
    assert isinstance(toolbox, EngineToolBox)
    controls = ScenarioControls(alternative_sailing_failure=True)
    run = WorkflowRun(
        run_id="agent-status-golden-0001",
        mode=RunMode.LIVE_STUB,
        controls=controls,
        scenario=scenario_with_controls(controls),
        toolbox=toolbox,
        brain=ScriptedBrain(),
    )
    run.start()

    await _wait_for(lambda: run.stage is WorkflowStage.DISPUTE and run.active_dispute is not None)
    dispute = run.active_dispute
    assert dispute is not None
    run.resolve_dispute(
        DisputeResolutionRequest(dispute_id=dispute.dispute_id, confirmed_constraint=CONSTRAINT)
    )

    await _wait_for(lambda: run.stage is WorkflowStage.AWAITING_APPROVAL or run.finished)
    assert run.stage is WorkflowStage.AWAITING_APPROVAL
    comparison = run.results.plan_comparison
    assert comparison is not None
    run.decide_approval(
        ApprovalRequest(plan_archetype=comparison.recommended, decision=ApprovalDecision.APPROVED)
    )
    await _wait_for(lambda: run.finished)
    # Annotated so the type checker widens back out of the AWAITING_APPROVAL
    # narrowing above; the approval is what moved the run on from there.
    final_stage: WorkflowStage = run.stage
    assert final_stage is WorkflowStage.COMPLETE

    return {
        "notice": "Generated by scripts/export_agent_status_golden.py. Do not hand-edit.",
        "final_stage": final_stage.value,
        # Only the fields both status machines read. Timings and ids would make
        # the fixture churn on every run without testing anything.
        "trace": [
            {
                "kind": event.kind.value,
                "stage": event.stage.value,
                "agent": event.agent.value if event.agent else None,
                "error": event.error,
            }
            for event in run.trace
        ],
        "activities": [
            {"agent": activity.agent.value, "status": activity.status.value}
            for activity in run.activities()
        ],
    }


def main() -> None:
    golden = asyncio.run(record_golden_run())
    GOLDEN_PATH.write_text(json.dumps(golden, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {GOLDEN_PATH}")


if __name__ == "__main__":
    main()
